spring:
  datasource:
    url : jdbc:mysql://3.37.185.108:3306/Trackify?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: JK
    password: 1111
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
#  jpa:
#    database: mysql
#    generate-ddl: true
#    show-sql: true
#  datasource:
#    url: jdbc:mysql://localhost:3306
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root1234!