spring:
#  jpa:
#    show-sql: true
#    properties:
#      format_sql: true
#      dialect: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: validate
#  datasource:
#    url: jdbc:mysql://localhost:3306
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root1234!

    datasource:
      url : jdbc:mysql://3.34.1.91:3306?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      dirver-class-name: com.mysql.cj.jdbc.Driver
      username: JK
      password: 1111
    jpa:
      database: mysql
      generate-ddl: true
      show-sql: true